language: python
python: 
  - "3.6"
script: 
  - pip3 install --upgrade pip setuptools wheel
  - python3 setup.py sdist bdist_wheel
  - python3 -m twine check dist/*
after_success:
  - python3 -m twine upload dist/* --username $UNAME -p $PASSWORD
after_script:
  - rm dist/*